language: node_js
node_js: 12
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: true
script:
  - npm run validate
skip_cleanup: true
after_success:
  - npm run report-coverage
  - npx semantic-release
